fix: added all contributors in footer
hackSocIndore/hackSocIndore.github.io pull request #38
Opened 2019-08-27 07:55 UTC by indraasura

Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

**Checklist:**

- [x] I have squashed my commits
- [x] My PR follows the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream development/master branch.

Changes:
Added remaining contributors in the footer

**Screenshots for the change**
![Screenshot_5](https://user-images.githubusercontent.com/17526377/63752048-2456d780-c8ce-11e9-8be6-9daa48d17a78.png)

2019-08-27 12:47 UTC, shashank-sharma requested changes
Few changes:
1. Fix `alt=Harshit` attribute with their respective names
2. Make sure that every contributor names is mentioned including you I guess
3. Cross check link and profile picture which were placed

2019-08-27 13:13 UTC, mishuvs commented
@indraasura you also didn't link the PR to the issue. This is important to automatically close the issue.

2019-08-30 09:08 UTC, indraasura commented
> @indraasura you also didn't link the PR to the issue. This is important to automatically close the issue.

Did that now

2019-08-30 09:09 UTC, indraasura commented
> Few changes:
> 
> 1. Fix `alt=Harshit` attribute with their respective names
> 2. Make sure that every contributor names is mentioned including you I guess
> 3. Cross check link and profile picture which were placed

Sure, will do it by today

2019-08-30 13:15 UTC, mishuvs commented on index.html
> +                                <img src="https://avatars3.githubusercontent.com/u/37576387?s=460&v=4" class="rounded-circle person" alt="Vaibhav Bhawalkar" width="40" height="40">
Wrong alt attribute, mistakenly interchanged

2019-08-30 13:17 UTC, mishuvs commented
Correct the names and squash the commits. Please complete it before the events one.

2019-08-30 13:39 UTC, mooocer requested changes
Small change left.

2019-08-31 05:15 UTC, closed without merging